### ISSUE TITLE
A way to specify links closer to the code.

### ISSUE THREAD

**Issue by oscarlvp** [apiad/illiterate#2]
The following is an example of a reference to another code element (class or module):

https://github.com/apiad/illiterate/blob/b11053b5b4271fb42191d6ed34947313747d2a12/illiterate/__init__.py#L172

However, it has to be specified thinking in the Markdown that will be generated. Could it be possible to make the reference using the code element, something like `ref::illiterate.code.Parser`?
This might require some mapping between the Python code and the Markdown documents to know the section where each class has been explained and will definitively make the parser more complex. But it might be a nice little touch :)

**Comment by apiad** [comment]
Yeah, I love that! It is definitely something I want to have. I think this would require automatically inserting some `<a/>` tags for every class (and method?) in the markdown. In any case, this will require a little bit more "parsing" of the Python source, maybe it's OK for an MVP to just check for a `r"class (.+):\n"` line instead of actually lifting the AST, but in the long run probably a full parsing of the code will be useful for a lot of these kind of tweaks.

**Comment by apiad** [comment]
So, I tried parsing the code with Python `ast` module. That's a definite no-no because first, it will drop comments (obviously :facepalm: ) and second we have no way to ensure we can dump the exact same code layout. So I kind of solved this with regexes by looking for `class` and `def` top-level definitions.

Now we output anchors for each of these, right before the Python block where they are defined. The bad news is that if you have more than one in the same Python block, all their anchors will point to the same block, not to individual lines inside the block because there is no easy way to inject HTML inside Markdown code blocks. But at least is something.

**Comment by apiad** [comment]
Ahh you still have to write the link as `module.md#class:ClassName`, instead of `module::ClassName`. Getting there requires a little bit of parsing of the Markdown content itself, which right now we just output verbatim. It is on the roadmap, though.

**Comment by apiad** [comment]
I think is ready now. You can reference any top-level type or method with `ref:module.name` and it will be automatically converted to the right path.
